# Generated by Django 5.0 on 2024-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
